export const LOGIN_STARTED = "LOGIN_STARTED";
export const LOGIN_STARTED_SUCCESS = "LOGIN_STARTED_SUCCESS";
export const LOGIN_STARTED_ERROR = "LOGIN_STARTED_ERROR";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const FETCH_USERS_STARTED = "FETCH_USERS_STARTED";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_ERROR = "FETCH_USERS_ERROR";
